from langchain_community.llms import Ollama
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.vectorstores import Chroma
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain.text_splitter import RecursiveCharacterTextSplitter

import os
from typing import List, Tuple

# =====================
# Configuration
# =====================

VECTOR_DB_DIR = "./vector_store"
LLM_MODEL = "llama3.1:8b"
EMBEDDING_MODEL = "znbang/bge:small-en-v1.5-f32"

# =====================
# Models
# =====================

llm = Ollama(
    model=LLM_MODEL,
    num_ctx=4096,
)

embeddings = OllamaEmbeddings(
    model=EMBEDDING_MODEL
)

# =====================
# Vector Store (Persistent)
# =====================

vector_store = Chroma(
    persist_directory=VECTOR_DB_DIR,
    embedding_function=embeddings,
)

retriever = vector_store.as_retriever(search_kwargs={"k": 2})

# =====================
# Text Splitting
# =====================

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    length_function=len,
)

# =====================
# Prompt
# =====================

PROMPT_TEMPLATE = """
Responda as perguntas baseado no contexto fornecido e no histórico da conversa.

Contexto:
{context}

Histórico da conversa:
{chat_history}

Pergunta:
{question}
"""

prompt = PromptTemplate.from_template(PROMPT_TEMPLATE)

# =====================
# Helpers
# =====================

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


def format_chat_history(
    history: List[Tuple[str, str]]
) -> str:
    if not history:
        return "Nenhuma conversa anterior."

    lines = []
    for user, assistant in history:
        lines.append(f"Usuário: {user}")
        lines.append(f"Assistente: {assistant}")
    return "\n".join(lines)

# =====================
# Document Ingestion
# =====================

def ingest_pdfs(file_paths: List[str]) -> None:
    """
    Load PDFs, split them, embed them and persist to disk.
    Safe to call multiple times.
    """
    documents = []

    for path in file_paths:
        if not os.path.exists(path):
            continue
        loader = PyPDFLoader(path)
        documents.extend(loader.load())

    if not documents:
        return

    splits = text_splitter.split_documents(documents)
    vector_store.add_documents(splits)

# =====================
# Chain Builder
# =====================


def create_chain_with_history(
    chat_history: List[Tuple[str, str]]
):
    return (
        {
            "context": retriever | format_docs,
            "question": RunnablePassthrough(),
            "chat_history": lambda _: format_chat_history(chat_history),
        }
        | prompt
        | llm
        | StrOutputParser()
    )

# =====================
# Streaming Support
# =====================

def stream_chain_with_history(chat_history: List[Tuple[str, str]], prompt_text: str):
    """
    Yields tokens as they are generated by the LLM for a given prompt and chat history.
    """

    llm_stream = Ollama(model=LLM_MODEL, num_ctx=4096)
    chain = (
        {
            "context": retriever | format_docs,
            "question": RunnablePassthrough(),
            "chat_history": lambda _: format_chat_history(chat_history),
        }
        | prompt
        | llm_stream
    )
    # Use the .stream() method for streaming
    for chunk in chain.stream(prompt_text):
        yield chunk

# =====================
# Example CLI Usage
# =====================

if __name__ == "__main__":
    # Run once to ingest PDFs
    ingest_pdfs(["3o_trimestre_2021.pdf"])

    history = []

    chain = create_chain_with_history(history)

    while True:
        question = input("\nVocê: ")
        if question.lower() in ("exit", "quit"):
            break

        answer = chain.invoke(question)
        print("\nAssistente:", answer)

        history.append((question, answer))
